### ISSUE TITLE
Can't open ifc models

### ISSUE THREAD

**Issue by OlliSchu** [jakob-beetz/IfcOpenShellScriptingTutorial#4]
Getting Error "UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 45: ordinal not in range(128)" when trying to open ifc model

**Comment by jakob-beetz** [comment]
Thanks for the report. 
It's an UTF8 encoding issue with Python 2.7

a dirty-hack to prevent this is to add the folloing in app.py
import sys
reload(sys)
sys.setdefaultencoding("utf-8")

note that this is not recommended : 
https://stackoverflow.com/questions/3828723/why-should-we-not-use-sys-setdefaultencodingutf-8-in-a-py-script

... but hey.. it works
